# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
#
# This template framework doesn't have dependencies itself, but provides 
# configuration for projects that will use the framework.
# 
# When you create a project from this template:
# 1. Update the reviewers field with your GitHub username
# 2. Remove ecosystems you don't use in your project
# 3. Add/remove directories as needed for your project structure

version: 2
updates:
  # GitHub Actions (for CI/CD workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "kholcomb"  # Replace with your GitHub username
    open-pull-requests-limit: 5

  # Example configurations for common project types
  # Uncomment and modify based on your project needs:

  # For Node.js projects (project/ directory)
  # - package-ecosystem: "npm"
  #   directory: "/project"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "04:00"
  #   labels:
  #     - "dependencies"
  #     - "npm"
  #   reviewers:
  #     - "kholcomb"
  #   open-pull-requests-limit: 10
  #   groups:
  #     npm-development:
  #       patterns:
  #         - "*"
  #       dependency-type: "development"
  #       update-types:
  #         - "minor"
  #         - "patch"

  # For Python projects (project/ directory)
  # - package-ecosystem: "pip"
  #   directory: "/project"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "dependencies"
  #     - "python"
  #   reviewers:
  #     - "kholcomb"

  # For Docker projects (project/ directory)
  # - package-ecosystem: "docker"
  #   directory: "/project"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "dependencies"
  #     - "docker"
  #   reviewers:
  #     - "kholcomb"

# Security updates are always given the highest priority