# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "your-github-username"  # Update this
    open-pull-requests-limit: 10
    # Group patch and minor updates together
    groups:
      npm-development:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      npm-production:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "patch"

  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "your-github-username"  # Update this
    open-pull-requests-limit: 10

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "your-github-username"  # Update this

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "your-github-username"  # Update this

# Security updates are always given the highest priority
# Dependabot will automatically create PRs for security updates
# regardless of the schedule defined above